#!/bin/bash

dac="$1"
main="$2"
out="$3"

pdftk "$dac" "$main" cat output "$out".tmp keep_final_id
# Hard code some value since these are not generated by xelatex but are generated by pdftk
meta=$(cat <<EOF
InfoBegin
InfoKey: ModDate
InfoValue: D:19700101000000-00&apos;00&apos;
InfoBegin
InfoKey: Creator
InfoValue: xelatex
EOF
       while read line; do
           if [[ "$line" =~ ^(BookmarkPageNumber|NumberOfPages|PageLabelNewIndex):\ *([0-9]*) ]]; then
               num=${BASH_REMATCH[2]}
               echo "${BASH_REMATCH[1]}: $((num + 1))"
           elif [[ "$line" =~ ^(PdfID0|PdfID1):\ *[0-9]* ]]; then
               echo "${BASH_REMATCH[1]}: 00000000000000000000000000000001"
           else
               echo "$line"
           fi
       done < <(pdftk "$main" dump_data))

pdftk "$out".tmp update_info <(echo "$meta") output "$out"
rm "$out".tmp
